### PR TITLE
Automated dependency upgrades

### PR DESCRIPTION
**Pull request by hc-github-team-secure-vault-ecosystem**
Full log: https://github.com/hashicorp/vault-plugin-auth-azure/actions/runs/10723236734

  IMPROVEMENTS:
* Updated dependencies:
   * `github.com/Azure/azure-sdk-for-go/sdk/azcore` v1.11.1 -> v1.14.0
   * `github.com/Azure/azure-sdk-for-go/sdk/azidentity` v1.5.2 -> v1.7.0
   * `github.com/coreos/go-oidc/v3` v3.10.0 -> v3.11.0
   * `github.com/hashicorp/vault/api` v1.13.0 -> v1.14.0
   * `github.com/hashicorp/vault/sdk` v0.12.0 -> v0.13.0
   * `github.com/microsoftgraph/msgraph-sdk-go` v1.42.0 -> v1.47.0
   * `github.com/microsoftgraph/msgraph-sdk-go-core` v1.1.0 -> v1.2.1
   * `golang.org/x/oauth2` v0.20.0 -> v0.23.0

### CODE REVIEW

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27322

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27322

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27322

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27322

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27322

**Review by Zlaticanin — APPROVED** [review]

**Pull request merged**
